name: logger-backend
services:
  app:
    build:
      context: .
      dockerfile: docker/php-server.Dockerfile
    ports:
      - 127.0.0.1:8080:80
    env_file:
      - .env
    environment:
      - LOGFILE_NAME="server-laravel.log"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:18
    env_file:
      - db.env
    volumes:
      - logger-postgres-data:/var/lib/postgresql/data
      - ./docker/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer:5
    ports:
      - 127.0.0.1:800:8080
    depends_on:
      - db

volumes:
  logger-postgres-data:
    name: logger-postgres-data
